apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-app
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
      - name: web-app
        image: gopiborra227/task-manager-app:v1

        ports:
        - containerPort: 6080
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "tasks_db"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-password
        