apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: applications
type: Opaque
stringData:
  # Kubernetes converts these plain text values into secure base64 blocks automatically
  postgres-username: "postgres"
  postgres-password: "MyHighlySecureEnterprisePassword2026!" # <-- MUST match your terraform.tfvars password